create table recipient (url varchar(255) not null, template_id varchar(255) not null, primary key (url))
create table templateParameters (template_id varchar(255) not null, templateParameters varchar(255) not null, primary key (template_id))
create table var_type (id bigint generated by default as identity, name varchar(255) not null, type varchar(255) not null, template_id varchar(255) not null, primary key (id))
alter table recipient add constraint FKpb2kfxmrw484emxr12bgi1bpx foreign key (template_id) references templateParameters
alter table var_type add constraint FK92dxftuwhx3h7am8m13302gav foreign key (template_id) references templateParameters
